### ISSUE TITLE
M3u8 the publication is incorrect

### ISSUE THREAD

**Issue by azizsan** [SamJUK/radio#2]
http://trkvz-radyo.ercdn.net/rdaspor/rdaspor_1.m3u8

m3u8 file format error

**Comment by SamJUK** [comment]
This is to do with m3u8 files not being audio files but playlist files that point to smaller HLS files with the stream data. I've added support for HLS files via HLS.JS, you can add more HLS file extensions in the array at the top of main.js if needs be.

**Comment by azizsan** [comment]
problem solved thanks :)
